### ISSUE TITLE
How to run benchmark on remote platforms via ssh?

### ISSUE THREAD

**Issue by DeeperMind** [ctuning/ck#102]
How to run benchmarks on remote platforms via ssh? For example, I have a Raspberry Pi connected to my Mac via ssh, and I want to benchmark the program in this Raspberry Pi from Mac. How to achieve this function?

**Comment by gfursin** [comment]
Hi @DeeperMind,

We have a mechanism to define remote devices as follows:
```
$ ck add machine:my-rpi3-ssh
```
CK will then ask you about how you would like to access your remove device:
