### ISSUE TITLE
when running 'install --rebuild', the --rebuild flag not get passed to dependencies

### ISSUE THREAD

**Issue by wildmetal** [ctuning/ck#104]
E.g. lib A depend on lib B, and when I run the 'ck install package --tags=lib,A...', it would clone lib B automatically and failed with some error in lib B. Then I modified the code in lib B which should work. But after I run the install command with --rebuild, it would clone lib B again and overwrite my modification.

**Comment by gfursin** [comment]
Hi @wildmetal . I added the functionality to pass --rebuild to all dependencies. Can you please try if it fixes your problem, please?

You need to update your ck-env repo to pick up my changes before reinstall your package:
```
ck pull repo:ck-env
```
Thanks!

**Comment by wildmetal** [comment]
The issue has gone with the update, thanks!

**Comment by gfursin** [comment]
Glad that it helped! Thanks for the feedback!
