### ISSUE TITLE
Travis issue "package writes outside sandbox"

### ISSUE THREAD

**Issue by jmrtin72** [ctuning/ck#108]
Travis can fail when I add ck as a dependency to my project with a message "package writes outside sandbox". Any ideas why?

**Comment by gfursin** [comment]
Thanks for reporting @jmrtin72! 

I think I know what is the problem: I copy the default CK repo (core CK modules) to $HOME/.ck directory during installation to help CK find it. But it seems to be "outside sandbox" for Travis. 

I tried to simplify our installer in the latest PR and do not copy default CK repo to $HOME/.ck. I just uploaded the pre-release version 1.12.3.3 to PYPI - can you please check if it solves your problem? 

Thanks!

**Comment by jmrtin72** [comment]
@gfursin, the problem seems to disappear in 1.12.3.3. thank.
