### ISSUE TITLE
ck steps for simple C-program with GNU compiler

### ISSUE THREAD

**Issue by sebk26** [ctuning/ck#136]
Hello,

i'm pretty new to ck and i'm struggling to set up a ck workflow for a simple C program.

So source files are `dummy.c` and `dummy.h`

Compiled by `gcc -o dummy dummy.c dummy-h -lm`

Can someone outline the steps i have to take? I dont find a way to register the gnu compiler. 
I downloaded ck-env and found my gcc compiler but don't know how to link that to my program.

So far:
1. pip install ck
2. ck pull repo:ck-env
3. ck add repo:dummyRepo --quiet
4. ck add dummyRepo:program:dummy
5. ck add module:dummy --func=compile
6. ck detect soft:compiler.gcc (interactively select appropriate)
7. ... ?

Best,
Sebastian

**Comment by gfursin** [comment]
Hi Sebastian! 
Thank you for your interest! 
We are preparing a few related tutorials at the moment.
CC @phesse001 - Patrick, you did a similar workflow recently - feel free to answer here.
I am a bit swamped finishing a few things but I will try to respond soon too.

**Comment by gfursin** [comment]
By the way, you do not need step 5. When you ran this command:
```
ck add dummyRepo:program:dummy
```
did CK ask you to select a template? If yes, you should have selected any C program. In such case, CK will prepare a dummy CK entry with a C source code inside and compiler dependency in the meta description of this entry. You can then go to this entry and edit both the source file and the meta to provide further info about command lines to run the code:
```
cd `ck find program:dummy`
more .cm/meta.json
```

You can then build and run this program as follows:
```
ck compile program:dummy
ck run program:dummy
```

**Comment by gfursin** [comment]
Here is the CK template for the basic C program: https://github.com/ctuning/ck-autotuning/tree/master/program/template-hello-world-c

Forgot to mention that you need "ck-autotuning" repo besides "ck-env" to use "program" API:
```
ck pull repo:ck-autotuning
```

**Comment by sebk26** [comment]
> By the way, you do not need step 5. When you ran this command:
> 
> ```
> ck add dummyRepo:program:dummy
> ```
> 
> did CK ask you to select a template? If yes, you should have selected any C program. In such case, CK will prepare a dummy CK entry with a C source code inside and compiler dependency in the meta description of this entry. You can then go to this entry and edit both the source file and the meta to provide further info about command lines to run the code:
> 
> ```
> cd `ck find program:dummy`
> more .cm/meta.json
> ```
> 
> You can then build and run this program as follows:
> 
> ```
> ck compile program:dummy
> ck run program:dummy
> ```

Hello Grigori,

Thank you very much for this super fast answer.
Apperently, i was not ask to select a template. Is there a flag or something similar to add to `ck add dummyRepo:program:dummy` to force a template or preselect one?

**Comment by sebk26** [comment]
Ok, with ck-autotuning, it was asked for a template.
So the workflow is now the following:

1. `pip install ck`
2. `ck pull repo:ck-env`
3. `ck pull repo:ck-autotuning`
4. `ck add repo:dummyRepo --quiet`
5. `ck add dummyRepo:program:dummy` **and select template**
6. `ck detect soft:compiler.gcc (interactively select appropriate)`
7. Manually change/add sourcefiles and compiler flags in .cm/meta.json

But i still need the manual part (7) or is there an automatic way?

**Comment by gfursin** [comment]
You are welcome!
Yes, I added a --template flag some time ago. Please do the following:
```
ck add dummyRepo:program:dummy --template=template-hello-world-c
```
You may need to delete the original entry first to start from scratch:
```
ck rm dummyRepo:program:dummy
```

Unfortunately, the step 7 is not yet automated. It's possible to do but we didn't have time yet.

By the way, you do not need to add compiler flags if you want to do autotuning. You can pass compiler flags to the program API as follows:
```
ck compile program:dummy --flags="-O3" --lflags="-lm"
```

Autotuners will generate those flags automatically...

BTW, I am gradually working on newer and cleaner API for the CK program module (and CK in general) - I hope to get a prototype out at some point in Q1 2021 ...

**Comment by phesse001** [comment]
Yup you will have to edit the meta.json file in dummyRepo/program/dummy/.cm if you want to substitute the template c file with your own (unless they are very similar).

I would recommend reading through the documentation [here](https://ck.readthedocs.io/en/latest/) if you haven't already as there is lot's of helpful information as well as checking out the [wiki](https://github.com/ctuning/ck/wiki) which has lot's of ck related articles, papers, and tutorials!

If you have more specific questions about your own workflow I would be happy to try to help as I have gone through similar steps myself

**Comment by sebk26** [comment]
> You are welcome!
> Yes, I added a --template flag some time ago. Please do the following:
> 
> ```
> ck add dummyRepo:program:dummy --template=template-hello-world-c
> ```
> 
> You may need to delete the original entry first to start from scratch:
> 
> ```
> ck rm dummyRepo:program:dummy
> ```
> 
> Unfortunately, the step 7 is not yet automated. It's possible to do but we didn't have time yet.
> 
> By the way, you do not need to add compiler flags if you want to do autotuning. You can pass compiler flags to the program API as follows:
> 
> ```
> ck compile program:dummy --flags="-O3" --lflags="-lm"
> ```
> 
> Autotuners will generate those flags automatically...
> 
> BTW, I am gradually working on newer and cleaner API for the CK program module (and CK in general) - I hope to get a prototype out at some point in Q1 2021 ...

Hello again, 
i had time to try out your suggestions and the following worked for me:

1. pip install ck
2. ck pull repo:ck-env
3. ck pull repo:ck-autotuning
4. ck add repo:dummyP --quiet
5. ck add dummyRepo:program:dummyP --template=template-hello-world-c
6. manually add `dummy.c` to source files in ~/CK/dummyRepo/program/dummyP/.cm/meta.json
7. copy source files (`dummy.c` and `dummy.h`) to ~/CK/dummyRepo/program/dummyP/
8. ck compile program:dummyP --flags="-lm" & *choose compiler interactively*
9. ck run program:dummyP & *choose `2) generic-linux`*

The compilation argument, you @gfursin were suggesting did not worked or i misunderstood the right place for it.
So i tried `ck compile program:dummy --flags="-O3" --lflags="-lm"` instead of step 8. but it did not understood the flag `"-03"`.

Other than that i will try this workflow now on a couple other examples and try to move them to other linux machines.

Thanks for now! I would leave this thread open, to update my findings, if this is ok.

**Comment by phesse001** [comment]
Without the error message it's hard to say why it didn't work, but that flag shouldn't be necessary unless you in fact want to use it. I think grigori was just adding that as an example of adding a compile flag.

If I had to guess I would say perhaps you typed "-03"(number 0) instead of "-O3"(capital o). This -O3 flag is an optional optimization flag that can be passed to potentially reduce code size and execution time but is not needed for the program to compile.

In this case if you were trying to reproduce the original command line you had the `--lflags="-lm"` would do it but if you had a more complex command line you could then add many link flags and compile flags to match your original command line. I hope this clears up some confusion!

**Comment by sebk26** [comment]
Oh, yes you're right. I just mistyped the `"-O3 "` and of course gcc does not know `"-03"`, sorry for bothering.

**Comment by gfursin** [comment]
Yes! That's right ;) !

**Comment by gfursin** [comment]
I guess this ticket is resolved - I close it.
