### ISSUE TITLE
Is env:python_simport used somewhere?

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck#149]
Hi @psyhtest and @ens-lg4,
Can you please tell me if you are using the [env:python_simport](https://github.com/ctuning/ai/tree/main/env/python_simport) component anywhere?
I can't find any reference to it.
I am cleaning and testing CK repositories and would like to remove unused or outdated components.
Thanks,
Grigori

**Comment by psyhtest** [comment]
We needed it for Quantum CK, IIRC.

**Comment by gfursin** [comment]
Oh, I see. Thanks @psyhtest. I didn't look at Quantum CK for a long time. 
Can you please remind me what IIRC is?

**Comment by ens-lg4** [comment]
As far as I know, we are not actively using this mechanism at the moment.

I think I kept it around as an example of "relocatable" env entry that contains relocatable importable code, and therefore does not need to be explicitly installed. It fits very well with the soft-package-env dependency resolution mechanism and is easy to use. The only drawback I remember was that it was permanently shown in the list of installed "env" entries, which confused some people (they could not "clean it up").

IIRC is an acronym for "if I remember correctly".

**Comment by ens-lg4** [comment]
@psyhtest, thanks, you are right!

Indeed, **ck-quantum:env:vqe_utils** is an entry which is based on **ck-env:env:python_simport** . I just wanted a very simple "template" for future reference.

**Comment by gfursin** [comment]
Great! Thank you @ens-lg4 and @psyhtest for the explanation! Makes sense!
