### ISSUE TITLE
$CK_HOST_CPU_NUMBER_OF_PROCESSORS undefined

### ISSUE THREAD

**Issue by hanwenzhu** [ctuning/ck#154]
In [this `make` statement in installing TVM from source](https://github.com/octoml/mlops/blob/d103ca7a0827809d32579627e6f67be7ac634fad/package/compiler-tvm-from-src/install.sh#L76) the environment variable `$CK_HOST_CPU_NUMBER_OF_PROCESSORS` is undefined, causing the `make -j` flag to think there are infinite jobs available.

Is this a problem with the meta description of this package installation (since I notice the variable is only available with `need_cpu_info` [here](https://github.com/ctuning/ck/blob/10b9e6424d0831f12272234d09eb1a6a572c3b2a/ck/repo/module/package/module.py#L784))? Or perhaps a default value (such as 1, 2, or 4) can always be done in the ck end, regardless of the package meta, to prevent such issues?

**Comment by gfursin** [comment]
Thank you for your feedback @hanwenzhu! I've noticed the same problem when compiling TVM. I will try to add some default value such as 2 for the TVM package. Will tell you when it's done.

**Comment by gfursin** [comment]
Hi Thomas,
I believe I've fixed that. Can you please update your AI repo and try again:
```
ck pull all
ck install package --tags=tvm,src
```
Thanks!

**Comment by gfursin** [comment]
I added new functionality to packages to set the number of processes for make (if supported by a given packge):
$ ck install package --j=4
Will be available in the release v2.5.6.

**Comment by hanwenzhu** [comment]
The issue is now fixed. Thank you!
