### ISSUE TITLE
Code duplication in MLPerf submission

### ISSUE THREAD

**Issue by hanwenzhu** [ctuning/ck#167]
There's a duplication [here](https://github.com/octoml/mlops/blob/e39e5757c698ba004b1bba7898a375e1755770c0/module/bench.mlperf.inference/module.py#L1530) — `framework_ext` is added twice to the SUT filename for JSON description

**Comment by gfursin** [comment]
Thank you very much, @hanwenzhu, for your feedback. I will fix that soon!

**Comment by gfursin** [comment]
Fixed! Thanks!
