### ISSUE TITLE
Installation of OpenME on OS X

### ISSUE THREAD

**Issue by CNugteren** [ctuning/ck#24]
I know that OS X isn't officially supported, so I understand that some features might not work. However, it would be nice if OpenME can be installed through ck on OS X.

If I follow the getting started guide, OpenME is automatically installed. However, this fails on my system:
```
cnugteren$ ck compile program:cbench-automotive-susan --speed
***************************************************************************************
Current directory: /Users/cnugteren/CK/ctuning-programs/program/cbench-automotive-susan/tmp
***************************************************************************************
Resolving dependencies ...
==========================================================================================
WARNING: environment was not found using tags="lib,xopenme" and setup={"target_os_bits": "64", "host_os_uoa": "linux-64", "target_os_uoa": "linux-64"}
  Would you like to search and install package with these tags automatically (Y/n)? Y
CK error: environment was not found using tags="lib,xopenme" and setup={"target_os_bits": "64", "host_os_uoa": "linux-64", "target_os_uoa": "linux-64"}!
```

When installing it explicitly, there is a more informative error message:
```
cnugteren$ ck install package:lib-rtl-xopenme

Resolving dependencies ...

Searching if environment already exists using:
  * Tags: lib,rtl,xopenme,lang-c,lang-cpp,lang-f77,lang-f90,lang-f95,v0.3,v0,host-os-linux-64,target-os-linux-64,64bits
  * Dependency: compiler=44609897464b20a3

Environment not found ...

*** Installation path used: /Users/cnugteren/CK-TOOLS/lib-rtl-xopenme-0.3-gcc-local-linux-64

Resolving dependencies ...

Copying XOpenME to src dir ...

Building static library ...

Executing gcc -O3 -fPIC -c  -I .     xopenme.c  
Executing ar rcs -o librtlxopenme.a xopenme.o
ar: illegal option combination for -r
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
Error: Compilation failed in /Users/cnugteren/CK-TOOLS/lib-rtl-xopenme-0.3-gcc-local-linux-64/src!
CK error: processing archive failed!
```

**Comment by gfursin** [comment]
Thanks for the feedback, Cedric!
Well, I have some descriptions of Mac OS (see ck list os), but it seems not to be properly detected.
In fact, I do not have Apple computers and couldn't check it.
However, the problem here is in -o flag in ar. I noticed that some OS has it and some not. I will need to think how to fix it without breaking compatibility ...

**Comment by gfursin** [comment]
As a temporal hack, you can find entry:
 ck find env:compiler-gcc-local-linux-h64-t64
and then edit 'env.sh'.
Just substitute
export CK_LB_OUTPUT="-o "
with
export CK_LB_OUTPUT=""

This should make examples work on your machine, while I look for better solution ;) ...

**Comment by gfursin** [comment]
The last: I did some changes in CK repositories, so before changing anything do
 ck pull all --kernel

**Comment by gfursin** [comment]
I think I made a proper fix: now CK should automatically detect that it runs on MacOS and select appropriate environment. I also added GCC description for MacOS where I removed -o flag from ar. 

Please, update all CK via
> ck pull all --kernel

Also, if you used above fixes, you can delete your local environments (they are wrong and for Linux anyway) via
 > ck rm local:env:*

Please, tell me this will work for you?

**Comment by CNugteren** [comment]
After `ck pull all --kernel` the installation of `package:lib-rtl-xopenme` finishes successful, so your fix works! However, I had to do this manually (using `ck install package:lib-rtl-xopenme`): the `ck compile program:cbench-automotive-susan --speed` command didn't manage to install the library itself (same behaviour as before).

**Comment by gfursin** [comment]
Cool. Good that manual installation works. It means that Mac OS is now properly detected. As for automatic installation - I need to check it. It's actually quite difficult without Mac OS (I need to talk to my colleagues - maybe they will lend me such laptop). I keep this ticket open and maybe will ask you a few more things to try later ...

**Comment by gfursin** [comment]
I think I found a problem. It's a stupid bug - when you answer 'Y' to install package automatically, I check "" not "Y" or "y" or "yes", so it quits with the last error. I fixed the problem and committed.
May I ask you to try again (just remove the environment for xopenme as I mentioned in a previous ticket). Thanks!

**Comment by CNugteren** [comment]
That's it! I removed `xopenme` and then asked to compile the example. It now correctly installs `xopenme` after typing `Y` and then compiles the example.

**Comment by gfursin** [comment]
Super! Sorry for a stupid glitch! Thanks!
