### ISSUE TITLE
Get rid of "integer version" for describing software.

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#30]
Currently the user has to provide an "integer version for comparison" (e.g. "for V5.2.3 use 50203"). This is unnecessary, as a simple Python function can perform string-to-integer conversions under the hood.

**Comment by gfursin** [comment]
I fixed that. It is possible to update via
$ ck pull repo:ck-env
I close the ticket - if someone finds problem, we can report it as a new issue ...
