### ISSUE TITLE
provide diagnostic about missing CK packages

### ISSUE THREAD

**Issue by syakush** [ctuning/ck#32]
current error messages are not intuitive, better diagnostic can be provided or CK packages can be installed automatically, on demand

**Comment by gfursin** [comment]
I think there is an easy solution to add "user friendly text" to dependencies meta. In such case, CK will print it and only then all tags. I will do it at some point ...

**Comment by gfursin** [comment]
I did a major update of CK env/soft/package manager, automated detection of software and provided user friendly names. I close this ticket. See related ticket here: https://github.com/ctuning/ck-env/issues/3

It is possible to get updated CK via:
$ ck pull all --kernel

If there is a problem with a given repository (too many changes), you can remove and reinstall it via
$ ck rm repo:{NAME} --all
$ ck pull repo:{NAME}
