### ISSUE TITLE
Simplify using SSH as Git protocol

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#34]
Currently the user [can specify](https://github.com/ctuning/ck/wiki/Hints-and-tips#changing-git-protocol-from-https-to-ssh) that she wants to use the SSH protocol by providing `--url=<...>` when cloning e.g.

<pre>
 $ ck pull repo:ctuning-programs --url=git@github.com:ctuning/ctuning-programs
</pre>

Since CK is hosted on GitHub, this could clearly be made less burdensome and error-prone e.g.
<pre>
 $ ck pull repo:ctuning-programs --ssh
</pre>

**Comment by gfursin** [comment]
Anton, I just realized that I already added this functionality a while ago. It's just that instead of --ssh I used --git. Can you please test that the following command works fine and then close this ticket:
$ ck pull repo:ctuning-programs --git

**Comment by psyhtest** [comment]
Yes, this works - thanks!
