### ISSUE TITLE
Non-uniform support for ISO time format in CK browser

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#35]
I have performed a [HOG experiment](https://github.com/ctuning/ck/wiki/Getting_started_guide_example_hog) and recorded its data into a local repository. I can view the created entry via a local webserver (`http://localhost:3344/?wcid=experiment:`) and on disk (`ck find experiment:* --tags=hog`). It is timestamped at `2015-09-04 13:29:20`. 

However, pasting this timestamp into the "After date (ISO)" filter in the CK browser (to filter out all but this entry) doesn't work - I need to replace the space in the timestamp with the 'T' character: `2015-09-04T13:29:20`

Now, Wikipedia says: "It is permitted to omit the 'T' character by mutual agreement." But the CK browser should either print the date format with 'T' or accept it without 'T'.

**Comment by gfursin** [comment]
I fixed that. You can now search with or without T. May I ask you to check it and close this ticket, please? Thanks!

**Comment by psyhtest** [comment]
Yep, works fine now - thanks!
