### ISSUE TITLE
Update .cm/meta.json on copy

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#41]
I've copied a repository like this:
```
$ ck cp reproduce-carp-project:program:realeyes-hog-opencl-tbb \
            reproduce-carp-project:program:new-hog-opencl-tbb 
Entry program:realeyes-hog-opencl-tbb was successfully copied!
```

Git reports new untracked files:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .cm/alias-a-new-hog-opencl-tbb
        .cm/alias-u-32d91de0c7049067
        new-hog-opencl-tbb/
```
Diff shows changes in `.cm/info.json`:
```
$ diff {realeyes,new}-hog-opencl-tbb/.cm/info.json 
2c2
<   "backup_data_uid": "b93bc750890706bc", 
---
>   "backup_data_uid": "32d91de0c7049067", 
19c19
<   "data_name": "realeyes-hog-opencl-tbb"
---
>   "data_name": "new-hog-opencl-tbb"
```
So far so good! However, there's no difference in `.cm/meta.json`:
```
$ diff {realeyes,new}-hog-opencl-tbb/.cm/meta.json
$
```
I'd expect it to be updated at least with the new UID (`32d91de0c7049067`)!

**Comment by gfursin** [comment]
Normally, I do not change .meta.json during copy (it is usually invariant of UID). 
'program' module has an exception - I added 'backup_data_uid' there to be able to trace original program UID even if you change it (for example, by accident) to be able to associate optimization info in shared databases. The idea was to change it manually for the moment. However, I can also overload copy/rename function in module 'program' and automatically change this UID (while warning authors about possible consequences). 

I will keep this ticket open and will check it in the future ...

**Comment by gfursin** [comment]
I fixed that!
