### ISSUE TITLE
Compilation on Windows fails when md5sum is unavailable

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#42]
Running a compile program on Windows e.g.
```
$ ck compile program:tool-print-cuda-devices
```
fails with "md5sum is not recognized as an internal or external command..."

I've nearly solved it by downloading "File Checksum Integrity Verifier" (`fciv.exe`) from [Microsoft](https://www.microsoft.com/en-gb/download/details.aspx?id=11533) into `~CK/ck/bin` and placing a file `md5sum.bat` there:
```
fciv.exe -md5 %1
```
But the Microsoft tool prints a comment before the actual checksum:
```
//
// File Checksum Integrity Verifier version 2.05.
//
2a084556e80926ce59f81cd51520ae08 a.exe
```
If this is an acceptable solution, CK should ignore the lines starting with `//`.

**Comment by gfursin** [comment]
Moved this ticket to ck-autotuning repo: https://github.com/ctuning/ck-autotuning/issues/8
