### ISSUE TITLE
ck find for repositories

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#45]
The `ck find` command for a repository returns the location of the locally stored *metadata* for this repository e.g.
```
anton@localhost / $ ck find repo:reproduce-carp-project
/home/anton/CK/local/repo/reproduce-carp-project
```
In most cases, however, the user will want to find the actual location of the *data*, not that of the *metadata*. Currently this can be found using the `ck where` command e.g.:
```
anton@localhost / $ ck where repo:reproduce-carp-project
/home/anton/CK/reproduce-carp-project
```
This is consistent with using `ck find` for other entities but not terribly intuitive, leading to confusion and frustration.

I suggest to change this behaviour, so that `ck find` returns the location of the *data*, while e.g. `ck find --meta` returns the location of the *metadata*. The `ck where` command can then be kept for compatibility or deprecated.

**Comment by gfursin** [comment]
I think I solved it. Can you please check it?

**Comment by psyhtest** [comment]
Verified with thanks!

```
anton@localhost / $ ck where repo:reproduce-carp-project       
/home/anton/CK/reproduce-carp-project
anton@localhost / $ ck find repo:reproduce-carp-project --meta
/home/anton/CK/local/repo/reproduce-carp-project
```
