### ISSUE TITLE
Public web service to find shared CK components by CID and redirect to a given third party repository similar to DOI

### ISSUE THREAD

**Issue by ctuning** [ctuning/ck#47]
With a growing number of shared CK components, we will need a public and stable web service
to find them by their CID and return an URL to a given repository (GitHUB, BitBucket, etc)...

**Comment by gfursin** [comment]
By the way, at the moment, DOI service for CK is via http://cknowledge.org/repo or via http://localhost/ck/repo/web.php?wcid=[CID]

**Comment by gfursin** [comment]
It's now done at https://cKnowledge.io .
