### ISSUE TITLE
Documentation: wrong command to run experiment

### ISSUE THREAD

**Issue by Krakonos** [ctuning/ck#49]
The documentation (https://github.com/ctuning/ck/wiki/Crowdsource_Experiments) states to run `ck crowdsource experiments`. I believe this is wrong, and should only state "experiment".

I know it's wiki, but it seems I can't edit it.

**Comment by gfursin** [comment]
That's right - it was a typo! Thanks a lot for noting! I fixed that!

**Comment by gfursin** [comment]
Hi Ladislav,
Looks like you need to be a part of the project to edit Wiki.
If you are interested, I can add you to this project ...
Thanks,
Grigori
