### ISSUE TITLE
run_and_get_stdout doesn't take into account quotes when receives a string as cmd

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck#59]
Hi, 

The following test should pass:

```python
    def test_run_and_get_stdout_2(self):
        r = ck.run_and_get_stdout({'cmd': 'sh -c "echo abcd && >&2 echo err && exit 2"'})
        self.assertEqual(0, r['return'])
        self.assertEqual(2, r['return_code'])
        self.assertEqual('abcd\n', r['stdout'])
        self.assertEqual('err\n', r['stderr'])
```

For now, it fails, because run_and_get_stdout doesn't take into account quotes when it splits string into parameters.

**Comment by gfursin** [comment]
Hi Dmitry, do you think you can fix it today (soon)? I would like to release a new CK version today (with all the new updates)! However, if it's not straightforward, we can leave it for the next release ... Thanks!

**Comment by dsavenko** [comment]
Initially I thought it would be hard, so created a task for the future. However, after some investigation I realized the fix is really simple. Prepared PR #60, please take a look (also added the test).
