### ISSUE TITLE
Use sort keys in compile_deps to specify linking order of libraries

### ISSUE THREAD

**Issue by michel-steuwer** [ctuning/ck#67]
**Problem:** Currently, the linking order of libraries specified as dependencies via `compile_deps` can't be specified.

**Proposed Solution:** The `sort` key could be used as an indication of linking order.

**Example:** Given this `.cm/meta.json` snippet from https://github.com/michel-steuwer/gemmbench
```
  "compile_deps": {
    "compiler": {
      "local": "yes", 
      "name": "C++ compiler", 
      "sort": 10, 
      "tags": "compiler,lang-cpp"
    }, 
    "lib-opencl": {
      "local": "yes", 
      "name": "OpenCL library", 
      "sort": 15, 
      "tags": "lib,opencl"
    },
    "lib-clblast-mali-overlay": {
      "add_to_path": "yes", 
      "local": "yes", 
      "name": "CLBlast library (Mali overlay)", 
      "sort": 20, 
      "tags": "lib,clblast,vmali-overlay"
    }, 
    "lib-clblast": {
      "local": "yes",
      "name": "CLBlast library (development)",
      "sort": 30,
      "tags": "lib,clblast,vdev"
    }
  }, 
```
I would expect the linking order to be `-lOpenCL -lclblast_mali -lclblast` where currently I get `-lclblast -lOpenCL-lclblast_mali`, as seen here:
```
g++-6    client.o utilities.o xgemm.o  -o clblast_client_xgemm.out    -L/home/michel/CK_TOOLS/lib-clblast-development-gcc-6.2.0-linux-32/lib -lclblast  -L/usr/share/OpenCL/r10p0-00rel0 -lOpenCL  -L/home/michel/CK_TOOLS/lib-clblast-mali-overlay-gcc-6.2.0-linux-32/lib -lclblast_mali -lm 
```

**Comment by psyhtest** [comment]
The `sort` key specifies the order in which CK resolves the dependencies. I can see that specifying the linking order would also be useful. I guess the question is whether the linking order should be the same as the current `sort` key, or should be available under a different key.

**Comment by gfursin** [comment]
I will check what happens now! I guess at the moment I do not sort this dictionary when adding libraries - in such case, re-using existing 'sort' key may work. I will tell you when I have more news ...

**Comment by gfursin** [comment]
I think I have fixed that. Now the order will be the same, as specified by 'sort' key in deps. It should be sufficient (I hope). May I ask you to check it, please? 
Don't forget to do 'ck pull all'
Thanks!

**Comment by michel-steuwer** [comment]
Great. I checked it and now the linking order is the same as specified by the `sort` keys.

**Comment by gfursin** [comment]
Cool! I repaid my Barcelona beer ;) ...
