### ISSUE TITLE
Simplify custom soft detection scripts

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#69]
CK users typically struggle to create custom detection scripts (i.e. `soft/*/customize.py`) for their software (e.g. libraries). 

They may start with a `customize.py` from another library but quickly get lost due to lack of comments and cryptic names.

Besides, such scripts are typically 3-4 KB in size but there's not a great deal of differences between them. Those difference that exist may add to the confusion e.g.
```
 $ diff $CK_REPOS/ck-env/soft/lib.{gflags,glog}/customize.py
115a116,118
>     ep=cus['env_prefix']
>     env[ep]=pi
>
131,133c134
<     ep=cus.get('env_prefix','')
<     if pi!='' and ep!='':
<        env[ep]=pi
---
>        env[ep+'_LFLAG']='-lglog'
```

We should refactor such scripts, outlining as much common stuff as possible, and provide clear, well-documented examples of scripts for detecting libraries, tools, etc

**Comment by gfursin** [comment]
Totally agree. Soft/package/env was heavily evolving during this year to quickly accomodate all requirements for automatic workflow deployment. After this experience, we discussed that we may need to redesign and clean it further. So, we either fix and document current scripts or possibly wait until we redesign CK soft/package functionality ... I am fine with both.

**Comment by dsavenko** [comment]
Yes, I'd like to do this task. While fixing https://github.com/ctuning/ck-autotuning/issues/17, I wanted to refactor the whole thing, but there was no time for that then. When I'm not so much occupied with https://github.com/dividiti/ck-zlib, I will think what we can do here and provide a proposal for discussion.

**Comment by gfursin** [comment]
I moved aged tickets without much activity to https://github.com/ctuning/ck/issues/150
