### ISSUE TITLE
Tab auto-completion

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck#73]
Hi,

A really awesome feature would be to support Bash tab auto-completion for CK. With long entity names, it's sometimes tiresome to type CK command, for instance `ck pull repo:crowdsource-video-experiments-on-desktop`.

Auto-completion, if done right, would allows users to tab-complete not only kernel CK actions, by also any module actions, entity (repo, module, dataset, etc) names, etc. This means the kernel would have to provide API interface for extending auto-completion in modules (implementing which in a module should not be obligatory).

Here's a link on programmable auto-completion in Bash: https://www.gnu.org/software/bash/manual/bash.html#Programmable-Completion

**Comment by gfursin** [comment]
That's a cool idea - if it's not make implementation more complex, that would be useful!

**Comment by gfursin** [comment]
Moved to https://github.com/ctuning/ck/issues/150
