### ISSUE TITLE
When renaming entries and data_name is the same as data_alias, update data_name too

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#81]
`data_name` is different from `data_alias` and `data_uid`. It can be set to a user-friendly string. By default, however, it is the same as `data_alias`.

At the moment, when a data entry is renamed, its `data_alias` changes, but `data_name` is kept the same. It makes sense if `data_name` is different from `data_alias` (i.e. it has been changed from the default). But it also makes sense to update `data_name` when it's the same as `data_alias`.

**Comment by gfursin** [comment]
I believe I fixed that. Can you please try new version from GitHub? Thanks!
