### ISSUE TITLE
"ck pull repo --url=https://github.com/dividity/ck-caffe" doesn't seem to work in my setup

### ISSUE THREAD

**Issue by sf-wind** [ctuning/ck#83]
I was following the documentation. When I tried to pull the repository, I got an error saying my user name and password authentication failed. I suppose it is because I used two-step authentication? 

After a few tries, CK did not ask me for my user name and password any more. Instead, it printed something like:

```
******************************************************************
Updating repo "ck-caffe" ...

  Local path: /Users/feisun/CK/ck-caffe
  URL:        https://github.com/dividity/ck-caffe

  cd /Users/feisun/CK/ck-caffe
  git pull

fatal: Not a git repository (or any of the parent directories): .git


 WARNING: repository update likely failed OR IN A DIFFERENT BRANCH/CHECKOUT (git exit code: 32768)

Would you like to continue (Y/n)?: y
  ========================================
  Checking dependencies on other repos ...
```

The directory is not a git repository. 

So, what is the work around to the issue? How to pull a repository? 

Thanks.

**Comment by gfursin** [comment]
Hi!
You made a typo: it should be dividiti instead of dividity. Where did you copy/paste this URL from? Maybe there is a mistake in the docs. You should do:
```
$ ck pull repo --url=https://github.com/dividiti/ck-caffe
```
Please tell me if it helps!

**Comment by sf-wind** [comment]
It is in the doc...

**Comment by psyhtest** [comment]
Thanks @sf-wind for reporting. I've fixed the typo [here](https://github.com/ctuning/ck/wiki/Portable-workflows). Does it work for you now?
