### ISSUE TITLE
we should fix a typo: https://github.com/ctuning/ck/wiki/Autotuning

### ISSUE THREAD

**Issue by w-simon** [ctuning/ck#89]
fixing typo

diff --git a/Autotuning.mediawiki b/Autotuning.mediawiki
index 874ae16..b7f6b80 100644
--- a/Autotuning.mediawiki
+++ b/Autotuning.mediawiki
@@ -629,7 +629,7 @@ for a new compiler version by copying the most close entry and updating
 its meta, for example creating meta for new GCC version 7.0.0 from 6.1.0:
 <pre>
  $ ck cp compiler:gcc-6.1.0-auto :gcc-7.0.0-user
- $ vim `ck find compiler:gcc-4.9.0-user`/.cm/desc.json
+ $ vim `ck find compiler:gcc-7.0.0-user`/.cm/desc.json
 </pre>
 
 Note, that we skipped module name in the second parameter ('':gcc-7.0.0-user''). 
@@ -642,7 +642,7 @@ you need to setup experimental pipeline from scratch via:
 
 <pre>
  $ rm _setup_program_pipeline_tmp.json
- $ ck pipeline program:cbench-automotive-susan --cmd_key=edges --compiler_description_uoa=gcc-4.9.0-user --prepare --save_to_file=_setup_program_pipeline_tmp.json
+ $ ck pipeline program:cbench-automotive-susan --cmd_key=edges --compiler_description_uoa=gcc-7.0.0-user --prepare --save_to_file=_setup_program_pipeline_tmp.json
 </pre>
 
 Note, that ''gcc-7.0.0-user'' entry was created in your local repository

**Comment by gfursin** [comment]
Fixed! Thanks for noting! BTW, if you are interested in autotuning, have a look at our last article in collaboration with Raspberry Pi foundation: http://cKnowledge.org/rpi-crowd-tuning
