### ISSUE TITLE
Adding repo from remote URL generates new UID instead of using one from .ckr.json

### ISSUE THREAD

**Issue by DaveGreasley** [ctuning/ck#91]
When adding a repo from a remote URL CK generates a new UID rather than using the one from .ckr.json. 

Steps to reproduce:

```
ck add repo:ck-rpi-optimization-results-reactions --zip=https://ndownloader.figshare.com/files/10218435 --quiet
```

Check .ckr.json for the ck-rpi-optimization-results-reactions:

<pre>
{
  <b>"data_uid": "d0714418b5886022",</b>
  "data_name": "ck-rpi-optimization-results-reactions",
  "data_alias": "ck-rpi-optimization-results-reactions",
  "data_uoa": "ck-rpi-optimization-results-reactions",
  "dict": {
     "repo_deps": [
       {
         "repo_uoa": "ck-rpi-optimization-results"
       }
     ]
  }
}
</pre>

Try to find repo by UID:

<pre>
dave@dave:CK$ ck find repo:d0714418b5886022
CK error: [repo] repository "d0714418b5886022" was not found in cache!
</pre>

Check CK cache json. The ID listed is not the same as the UID from the repo json. Also each time this repository is pulled down a new ID will be generated.

<pre>
{
  "ck-env": "1ff43ae88715a8c1",
  "ck-assets": "4784a9da122ed85c",
  "ck-dissemination-modules": "62a4f46acf5ff29e",
  "ck-web": "215d441c19db1fed",
  "ck-rpi-optimization-results-reactions2": "03884ab4e0d94d1b",
  "ck-rpi-optimization": "4439c9443bbab749",
  "ctuning-programs": "1db88c44a4086634",
  "ctuning-datasets-min": "4ffcc1307484d840",
  "ck-rpi-optimization-results": "147d284ae646bb5a",
  "ck-crowdtuning-platforms": "168cb19e71ad2493",
  "ck-docker": "18bb3d4130a4aaf9",
  <b>"ck-rpi-optimization-results-reactions": "1e4528b30c7fe00e",</b>
  "ck-crowdtuning": "c7e5332641d8922a",
  "ck-autotuning": "a4328ba99679e0d1",
  "ck-analytics": "76c4424a1473c873",
  "remote-ck": "36a94d813c46d497"
}
</pre>

**Comment by gfursin** [comment]
Thanks a lot, Dave, for noting this issue. I committed your fix!
