### ISSUE TITLE
why can't find path

### ISSUE THREAD

**Issue by SuperPowerLF2** [ctuning/ck#95]
I did that

You can try to install CK as described here: https://github.com/ctuning/ck#windows
and then try to install Caffe using related CK package:

$ ck pull repo --url=https://github.com/dividiti/ck-caffe
$ ck install package:lib-caffe-bvlc-master-cudnn-universal --env.CAFFE_BUILD_PYTHON=ON
CK should automatically detect your Visual Studio, CUDA, cuDNN and attempt to build Caffe - hope it will work ...

From the back of my mind, I didn't have problems with CUDA 9.0 when using VS 2015. Current problems are when using CUDA 9.x with the latest VS 2017 release.

find is ok
C:\Users\LF2>ck find repo:ck-caffe
C:\Users\LF2\CK\ck-caffe
install is error...
C:\Users\LF2>ck install package:lib-caffe-bvlc-master-cudnn-universal --env.CAFFE_BUILD_PYTHON=ON
CK error: [package] can't find path to CK entry "module:package" (?:032630d041b4fd8a:?)!

I don't know what to do...

**Comment by psyhtest** [comment]
@SuperPowerLF2 That's very weird. `module:package` is in `repo:ck-env`:
```
$ ck find module:package
/home/anton/CK_REPOS/ck-env/module/package
```
which should be pulled in by CK due to the dependencies.

Could you please do:
```
$ ck pull repo:ck-env
```
and try again?

**Comment by gfursin** [comment]
Hi @SuperPowerLF2 . Yes, looks like somehow ck-env was not pulled. 

Can you please also list what is in your C:\Users\LF2\CK directory?

You can also try to update all repositories as follows and then try again:
```
$ ck pull all
```

Thanks!

**Comment by gfursin** [comment]
I guess this issue is resolved. I close it.
