### ISSUE TITLE
CK new year wishes - feel free to add your own!

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck#96]
Hi all,

I started collecting different CK wishes for 2019 here:

1) start preparing different "How to guides": "how to create a module", "how to create a software detection plugin", "how to create different types of packages (code, data sets, models)", "how to create a program workflow", etc.
2) update CK contributor guide 
3) start standardizing all APIs of shared modules: http://cKnowledge.org/shared-modules.html
4) add continuous testing of shared CK packages across different compilers, platforms and sub-dependencies: http://cKnowledge.org/shared-packages.html
5) add continuous testing of all program workflows: http://cKnowledge.org/shared-programs.html
6) improve soft/package modules and meta descriptions (make them simpler and move different functionality from OS-dependent scripts to Python)
7) improve support for spack and easybuild
8) improve automatic generation of reproducible articles based on http://cKnowledge.org/rpi-crowd-tuning
9) improve CK workflows to crowd-source AI/ML/SW/HW autotuning and co-design: https://github.com/ctuning/ck-mlperf , http://cKnowledge.org/request and http://cknowledge.org/android-apps.html

Please feel free to add your own wishes with some ideas about to achieve them! Also please indicate if you can help yourself or provide resources - as a non-profit community project, we have limited resources and rely on your help! 

Looking forward to further collaboration to improve our open R&D platform in 2019!

**Comment by gfursin** [comment]
Improve high-level overview of CK capabilities and program workflows: http://cknowledge.org/high-level-overview.pdf - feedback is welcome!

**Comment by gauravkaul** [comment]
- Look into ONNX runtimes and other similar inference optimized runtimes for heterogeneous hardware (e.g. the Microsoft ONNX Runtime - https://github.com/Microsoft/onnxruntime
AWS Neo based on TVM - https://aws.amazon.com/sagemaker/neo/

**Comment by gfursin** [comment]
After the 1st Quantum Machine Learning hackathon in Paris, we got a feedback to provide a simpler installer: https://github.com/ctuning/ck/issues/98

**Comment by psyhtest** [comment]
For automatic testing, it would be handy to check out a particular revision of a repository or branch e.g.:
```
$ ck pull repo:ck-tensorflow --git_hash=655a20f99af32926cbf6d8fab092506ddd70e49c
```
or:
```
$ ck pull repo:ck-tensorflow --git_branch=object-detection-tflite
```

**Comment by psyhtest** [comment]
Another handy feature would be to search preprocessing/postprocessing scripts by tags, so, for example, instead of [hard-coding](https://github.com/ctuning/ck-tensorflow/blob/master/program/image-classification-tf-cpp/.cm/meta.json#L55):
```
        "pre_process_via_ck": {
          "data_uoa":       "b98ee24399ef4c3a",
          "module_uoa":     "script",
          "script_name":    "preprocess"
        },
```
one could use:
```
        "pre_process_via_ck": {
          "tags": "image-classification,imagenet,tf",
          "module_uoa":     "script",
          "script_name":    "preprocess"
        },
```

**Comment by gfursin** [comment]
We already addressed some of these issues and together with OctoML we started adding support for the ONNX runtime.
I close this ticket and move some ideas to https://github.com/ctuning/ck/issues/150 .
