### ISSUE TITLE
Where did cTuning CC move?

### ISSUE THREAD

**Issue by zaoqi** [ctuning/ck#99]
http://ctuning.org/wiki/index.php/CTools:CTuningCC

**Comment by gfursin** [comment]
Hi! It's moved here: 
* http://crowd-research.com/c.php?cid=4adfaff6d69d41a9:9482c22d7601b0df
* https://github.com/ctuning/reproduce-milepost-project

**Comment by thoward27** [comment]
Thanks for pointing out that newer resource, however it still does not work for native builds. See #100 for details on other things I've tried, how can I reproduce milepost locally?

**Comment by gfursin** [comment]
Thanks @thoward27 - I close this issue and will continue working on #100 ;) .
